### ISSUE TITLE
Damage done by friend / party shows up as Unkown

### ISSUE THREAD

**Issue by KBoumghar** [SuperNerdEric/combat-logger#1]
When looking at damage done of a boss done with a friend, I get an "unknown" category, which I assume is the friend I was with (maybe also thrall...?) :

![image](https://github.com/user-attachments/assets/c8504ba5-7e7f-4bfc-8e10-eecf221d2db2)

Weirdly enough, I do not have this issue for damage taken : 

![image](https://github.com/user-attachments/assets/ccedd908-110b-4a21-9522-0dd19ab54ad6)

Would it be possible to have the damage done separated by friend source (like damage taken)? Or atleast a better description than "unkown" (do these include thralls?).

I do not know if the issue arrives from Combat Logger or Runelogs, but I assume it is Combat logger. Feel free to correct me.

Thanks !

**Comment by SuperNerdEric** [comment]
Hi @KBoumghar,

Damage done by other players can only be detected if the other player(s) are in a Party with you and they also have to have the Combat Logger plugin. This is because of a limitation in RuneLite where you can not see the source of damage (unless it's your own because those are different colored hitsplats). If you use the "Party" plugin and join in a RuneLite party together the plugin will automatically send messages to each other to tell you the source of the damage.

Your thrall damage should count towards yourself as they are the same color hitsplat are yours.

Joining a Party should solve your issue, but there are a few other cases where the damage can be "Unknown" and I don't currently have a good way to detect it. It can happen when an NPC damages another NPC (like the exploding monkeys in ToA or when Verzik damages the pillars). But those should only be on specific fights that have mechanics like that.
